apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: podinfo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - ./podinfo
          - --port={{ .Values.service.port | default 9898 }}
          env:
          {{- if .Values.ui.message }}
          - name: PODINFO_UI_MESSAGE
            value: {{ quote .Values.ui.message }}
          {{- end }}
          {{- if .Values.ui.color }}
          - name: PODINFO_UI_COLOR
            value: {{ quote .Values.ui.color }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 9898 }}
              protocol: TCP
