apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo1
  namespace: argocd
spec:
  project: default
  source:
    path: "helm"
    repoURL: "https://github.com/PTarasyuk/tf-eks-argo"
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      parameters:
      - name: "image.tag"
        value: 6.5.1
      - name: "ui.message"
        value: "Hello from PODINFO #1"
      - name: "ui.color"
        value: "#34577c"
  destination:
    name: in-cluster
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true         